// source: tcbs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck


goog.provide('proto.tcbs.BuySellActivePojo');
goog.provide('proto.tcbs.InvestorHistoryTrade');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tcbs.BuySellActivePojo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tcbs.BuySellActivePojo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tcbs.BuySellActivePojo.displayName = 'proto.tcbs.BuySellActivePojo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tcbs.InvestorHistoryTrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tcbs.InvestorHistoryTrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tcbs.InvestorHistoryTrade.displayName = 'proto.tcbs.InvestorHistoryTrade';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tcbs.BuySellActivePojo.prototype.toObject = function(opt_includeInstance) {
  return proto.tcbs.BuySellActivePojo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tcbs.BuySellActivePojo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.BuySellActivePojo.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
    closeprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    closevol: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    change: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    reference: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    totaltrading: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    totaltradingvalue: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    timesec: jspb.Message.getFieldWithDefault(msg, 8, 0),
    action: jspb.Message.getFieldWithDefault(msg, 9, ""),
    unittimeframe: jspb.Message.getFieldWithDefault(msg, 10, 0),
    tradingvalue: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0),
    buyupacc: jspb.Message.getFloatingPointFieldWithDefault(msg, 12, 0.0),
    selldownacc: jspb.Message.getFloatingPointFieldWithDefault(msg, 13, 0.0),
    highlight: jspb.Message.getBooleanFieldWithDefault(msg, 14, false),
    bidprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 15, 0.0),
    bidvol: jspb.Message.getFloatingPointFieldWithDefault(msg, 16, 0.0),
    askprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 17, 0.0),
    askvol: jspb.Message.getFloatingPointFieldWithDefault(msg, 18, 0.0),
    prevchange: jspb.Message.getFloatingPointFieldWithDefault(msg, 19, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tcbs.BuySellActivePojo}
 */
proto.tcbs.BuySellActivePojo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tcbs.BuySellActivePojo;
  return proto.tcbs.BuySellActivePojo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tcbs.BuySellActivePojo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tcbs.BuySellActivePojo}
 */
proto.tcbs.BuySellActivePojo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCloseprice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClosevol(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setChange(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setReference(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotaltrading(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotaltradingvalue(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimesec(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUnittimeframe(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTradingvalue(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBuyupacc(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSelldownacc(value);
      break;
    case 14:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHighlight(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBidprice(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBidvol(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAskprice(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAskvol(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrevchange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tcbs.BuySellActivePojo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tcbs.BuySellActivePojo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tcbs.BuySellActivePojo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.BuySellActivePojo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCloseprice();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClosevol();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getChange();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getReference();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTotaltrading();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getTotaltradingvalue();
  if (f !== 0.0) {
    writer.writeDouble(
      7,
      f
    );
  }
  f = message.getTimesec();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getUnittimeframe();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getTradingvalue();
  if (f !== 0.0) {
    writer.writeDouble(
      11,
      f
    );
  }
  f = message.getBuyupacc();
  if (f !== 0.0) {
    writer.writeDouble(
      12,
      f
    );
  }
  f = message.getSelldownacc();
  if (f !== 0.0) {
    writer.writeDouble(
      13,
      f
    );
  }
  f = message.getHighlight();
  if (f) {
    writer.writeBool(
      14,
      f
    );
  }
  f = message.getBidprice();
  if (f !== 0.0) {
    writer.writeDouble(
      15,
      f
    );
  }
  f = message.getBidvol();
  if (f !== 0.0) {
    writer.writeDouble(
      16,
      f
    );
  }
  f = message.getAskprice();
  if (f !== 0.0) {
    writer.writeDouble(
      17,
      f
    );
  }
  f = message.getAskvol();
  if (f !== 0.0) {
    writer.writeDouble(
      18,
      f
    );
  }
  f = message.getPrevchange();
  if (f !== 0.0) {
    writer.writeFloat(
      19,
      f
    );
  }
};


/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.tcbs.BuySellActivePojo.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double closeprice = 2;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getCloseprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setCloseprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double closevol = 3;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getClosevol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setClosevol = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double change = 4;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double reference = 5;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getReference = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setReference = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double totaltrading = 6;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getTotaltrading = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setTotaltrading = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional double totaltradingvalue = 7;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getTotaltradingvalue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setTotaltradingvalue = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional int64 timesec = 8;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getTimesec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setTimesec = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string action = 9;
 * @return {string}
 */
proto.tcbs.BuySellActivePojo.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 unittimeframe = 10;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getUnittimeframe = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setUnittimeframe = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional double tradingvalue = 11;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getTradingvalue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setTradingvalue = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


/**
 * optional double buyupacc = 12;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getBuyupacc = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 12, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setBuyupacc = function(value) {
  return jspb.Message.setProto3FloatField(this, 12, value);
};


/**
 * optional double selldownacc = 13;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getSelldownacc = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 13, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setSelldownacc = function(value) {
  return jspb.Message.setProto3FloatField(this, 13, value);
};


/**
 * optional bool highlight = 14;
 * @return {boolean}
 */
proto.tcbs.BuySellActivePojo.prototype.getHighlight = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 14, false));
};


/**
 * @param {boolean} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setHighlight = function(value) {
  return jspb.Message.setProto3BooleanField(this, 14, value);
};


/**
 * optional double bidprice = 15;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getBidprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 15, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setBidprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 15, value);
};


/**
 * optional double bidvol = 16;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getBidvol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 16, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setBidvol = function(value) {
  return jspb.Message.setProto3FloatField(this, 16, value);
};


/**
 * optional double askprice = 17;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getAskprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 17, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setAskprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 17, value);
};


/**
 * optional double askvol = 18;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getAskvol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 18, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setAskvol = function(value) {
  return jspb.Message.setProto3FloatField(this, 18, value);
};


/**
 * optional float prevchange = 19;
 * @return {number}
 */
proto.tcbs.BuySellActivePojo.prototype.getPrevchange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 19, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.BuySellActivePojo} returns this
 */
proto.tcbs.BuySellActivePojo.prototype.setPrevchange = function(value) {
  return jspb.Message.setProto3FloatField(this, 19, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tcbs.InvestorHistoryTrade.prototype.toObject = function(opt_includeInstance) {
  return proto.tcbs.InvestorHistoryTrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tcbs.InvestorHistoryTrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.InvestorHistoryTrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
    avgprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    closevol: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    change: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    reference: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    totalvalue: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    timesec: jspb.Message.getFieldWithDefault(msg, 7, 0),
    action: jspb.Message.getFieldWithDefault(msg, 8, ""),
    type: jspb.Message.getFieldWithDefault(msg, 9, ""),
    notrans: jspb.Message.getFieldWithDefault(msg, 10, 0),
    unittimeframe: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tcbs.InvestorHistoryTrade}
 */
proto.tcbs.InvestorHistoryTrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tcbs.InvestorHistoryTrade;
  return proto.tcbs.InvestorHistoryTrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tcbs.InvestorHistoryTrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tcbs.InvestorHistoryTrade}
 */
proto.tcbs.InvestorHistoryTrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAvgprice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClosevol(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setChange(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setReference(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalvalue(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimesec(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNotrans(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUnittimeframe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tcbs.InvestorHistoryTrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tcbs.InvestorHistoryTrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tcbs.InvestorHistoryTrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.InvestorHistoryTrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAvgprice();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClosevol();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getChange();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getReference();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTotalvalue();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getTimesec();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getNotrans();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getUnittimeframe();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
};


/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double avgprice = 2;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getAvgprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setAvgprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double closevol = 3;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getClosevol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setClosevol = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double change = 4;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double reference = 5;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getReference = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setReference = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double totalvalue = 6;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getTotalvalue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setTotalvalue = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int64 timesec = 7;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getTimesec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setTimesec = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string action = 8;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string type = 9;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 notrans = 10;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getNotrans = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setNotrans = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int64 unittimeframe = 11;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getUnittimeframe = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setUnittimeframe = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


