// source: tcbs.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck


goog.provide('proto.tcbs.InvestorHistoryTrade');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.tcbs.InvestorHistoryTrade = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.tcbs.InvestorHistoryTrade, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.tcbs.InvestorHistoryTrade.displayName = 'proto.tcbs.InvestorHistoryTrade';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.tcbs.InvestorHistoryTrade.prototype.toObject = function(opt_includeInstance) {
  return proto.tcbs.InvestorHistoryTrade.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.tcbs.InvestorHistoryTrade} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.InvestorHistoryTrade.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
    avgprice: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    closevol: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    change: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    reference: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    totalvalue: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    timesec: jspb.Message.getFieldWithDefault(msg, 7, 0),
    action: jspb.Message.getFieldWithDefault(msg, 8, ""),
    type: jspb.Message.getFieldWithDefault(msg, 9, ""),
    notrans: jspb.Message.getFieldWithDefault(msg, 10, 0),
    unittimeframe: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.tcbs.InvestorHistoryTrade}
 */
proto.tcbs.InvestorHistoryTrade.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.tcbs.InvestorHistoryTrade;
  return proto.tcbs.InvestorHistoryTrade.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.tcbs.InvestorHistoryTrade} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.tcbs.InvestorHistoryTrade}
 */
proto.tcbs.InvestorHistoryTrade.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAvgprice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setClosevol(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setChange(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setReference(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotalvalue(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimesec(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setAction(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNotrans(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUnittimeframe(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.tcbs.InvestorHistoryTrade.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.tcbs.InvestorHistoryTrade.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.tcbs.InvestorHistoryTrade} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.tcbs.InvestorHistoryTrade.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAvgprice();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getClosevol();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getChange();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getReference();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getTotalvalue();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getTimesec();
  if (f !== 0) {
    writer.writeInt64(
      7,
      f
    );
  }
  f = message.getAction();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getNotrans();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getUnittimeframe();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
};


/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double avgprice = 2;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getAvgprice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setAvgprice = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double closevol = 3;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getClosevol = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setClosevol = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double change = 4;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getChange = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setChange = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double reference = 5;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getReference = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setReference = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double totalvalue = 6;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getTotalvalue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setTotalvalue = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int64 timesec = 7;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getTimesec = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setTimesec = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string action = 8;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getAction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setAction = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string type = 9;
 * @return {string}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 notrans = 10;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getNotrans = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setNotrans = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int64 unittimeframe = 11;
 * @return {number}
 */
proto.tcbs.InvestorHistoryTrade.prototype.getUnittimeframe = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.tcbs.InvestorHistoryTrade} returns this
 */
proto.tcbs.InvestorHistoryTrade.prototype.setUnittimeframe = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


